# Either simple list all your repositories, e.g.:
#
# repositories:
#   - http://anycontent.dev/1/example1
#   - http://anycontent.dev/1/example2
#
# or give them shortcuts, so you can reference them in your code or in advanced configurations, e.g.:
#
# repositories:
#   shortcut1: http://anycontent.dev/1/example1
#   shortcut2: http://anycontent.dev/1/example2
#

repositories:
  - http://anycontent.dev/1/example


userinfo:
  username:   john@example.org
  firstname:  John
  lastname:   Doe

#
# cache settings
#
# seconds_caching_api_responses determines how long a api result gets cached. It will get invalid, if you
# perform a write operation.
# seconds_ignoring_eventually_concurrent_writes determines how often you request the repositoy info. If set to 0
# you might perform multiple requests during one operation, so better keep the default of 1 second. If your client
# is the only client operating with the API, you can raise the value, otherwise keep it low to avoid confusing results.
#

cache:
  driver: {type: apc}
  seconds_caching_menu: 600
  seconds_caching_api_responses: 3600
  seconds_ignoring_eventually_concurrent_writes: 1
  seconds_ignoring_eventually_concurrent_file_updates: 15


authentication:
  type: config
  users:
     - {username: john@example.org, firstname: John, lastname: Doe, password: john@example.org, encryption: none }