repositories:
  - http://anycontent.dev/1/example
  #- http://anycontent.dev/1/demo
  #- http://anycontent.dev/1/nhagemann
  - http://acrs.hahnair.dev/1/portal
  - http://acrs.hahnair.dev/1/quickcheck
  #- http://anycontent.dev/1/telecolumbus

userinfo:
  username:   mail@nilshagemann.de
  firstname:  Nils
  lastname:   Hagemann

